# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20161126_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='main.Station'),
        ),
    ]
