# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20161127_0901'),
        ('main', '0008_auto_20161127_0756'),
    ]

    operations = [
    ]
